name: Test

on: [push]

jobs:
    test:

        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [7.4]
                laravel: [7.*]
                dependency-version: [prefer-stable]
                include:
                    -   laravel: 7.*
                        testbench: 5.*


        name: P ${{ matrix.php }} - L ${{ matrix.laravel }} - ${{ matrix.dependency-version }}

        steps:
            -   name: Install chatter-app app
                run:  composer create-project --prefer-dist laravel/laravel chatter-app "${{ matrix.laravel }}"

            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick

            -   name: Install dependencies
                working-directory: ./chatter-app
                run: |
                    composer require "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            -   name: Prepare Laravel Application
                working-directory: ./chatter-app
                run: |
                    cp .env.example .env
                    php artisan key:generate
                    php artisan ui bootstrap --auth
                    php artisan vendor:publish --all

            -   name: Prepare Laravel Database
                working-directory: ./chatter-app
                env:
                  APP_ENV: testing
                  DB_CONNECTION: sqlite
                  DB_DATABASE: database/database.sqlite
                run: |
                  touch database/database.sqlite
                  php artisan migrate --verbose
                  php artisan db:seed --class=ChatterTableSeeder
                  vendor/bin/phpunit vendor/abr4xas/chatter

            -   name: Execute tests
                working-directory: ./chatter-app
                run: vendor/bin/phpunit vendor/abr4xas/chatter

            -   name: Upload artifacts
                uses: actions/upload-artifact@master
                if: failure()
                with:
                    name: Logs
                    path: ./storage/logs